### PR TITLE
Add support for PICO-8 carts with standalone fake08

### PR DESCRIPTION
**Pull request by TechDevangelist**
Not sure if there is a desire to add other emulators, but here is the fake08 binary from OnionOS, plus some additional code borrowed code from @erazemk to prompt users about lack of auto saving.

### CODE REVIEW

**Comment by tiduscrying** [comment]
Very intrigued by this. Out of curiosity, does this utilize the MiniUI menus at all or is it completely stand-alone? I'll have to give it a whirl after work, but after that I'll merge it sometime this weekend hopefully. Thanks!

**Comment by TechDevangelist** [comment]
Sadly, it's completely standalone as it's not a libretro core so the built-in menu within MiniUI isn't present & auto save won't work. There was another core option based on libretro (retro8) but didn't seem to support newer carts. fake08 seemed to have better support for newer carts though which is what OnionOS moved to.

**Comment by erazemk** [comment]
> Out of curiosity, does this utilize the MiniUI menus at all or is it completely stand-alone?

Yes, launch.sh, lines 14-20, requires MiniUI specific files (png resources and binaries like `show`, `confirm` and `say`) to show the autosave message.

**Comment by tiduscrying** [comment]
Just tried out the pak and it works pretty well with just about everything I've tossed at it. Is there sound support though?

**Comment by tiduscrying** [comment]
Know what, it looks like it was something on my end. I was using a nightly that had some changes to the audio server that must have also been causing the audio to not work. Updating to a newer nightly that reverted the change fixed it and now I'm getting sound with Picohot.

**Pull request merged**
